included:
  - Sources
  - Tests
excluded:
  - .build
  - Tests/ScipioKitTests/Resources/Fixtures
disabled_rules:
  - nesting
  - function_parameter_count
  - force_try
  - todo
  - function_body_length
  - cyclomatic_complexity
line_length: 150
