included:
  - Sources
  - Tests
excluded:
  - .build
  - Tests/ScipioKitTests/Resources/Fixtures
  - Sources/ScipioKit/SwiftPM/Version.swift
disabled_rules:
  - function_parameter_count
  - force_try
  - todo
  - cyclomatic_complexity
  - optional_data_string_conversion
line_length:
  warning: 150
  ignores_comments: true
file_length: 600
nesting:
  type_level: 3
function_body_length:
  warning: 75
trailing_comma:
  mandatory_comma: true
type_body_length:
  warning: 400
