name: Lint

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  SwiftLint:
    strategy:
      matrix:
        xcode_version: ["15.2"]
    env: 
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer"
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2
    - name: SwiftLint
      run: swiftlint --strict
