name: Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  Tests:
    strategy:
      matrix:
        xcode_version:
          - "15.2" # 5.9
          - "15.4" # 5.10
          - "16.0" # 6.0
    env: 
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer"
    runs-on: macos-14
    steps:
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        swift test --verbose
      env:
        ENABLE_INTEGRATION_TESTS: 1
        IS_CI: 1
