name: Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  Tests:
    strategy:
      matrix:
        xcode_version: ["15.2"]
        swift: ["5.8.1", "5.9.2", "5.10.0"]
    env: 
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer"
    runs-on: macos-13
    steps:
    - uses: SwiftyLab/setup-swift@latest
      with:
        development: true
        swift-version: ${{ matrix.swift }}
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        # If default toolchain in Xcode is used, `env.TOOLCHAINS` will be empty
        if [[ -n "${{ env.TOOLCHAINS }}" ]]; then
          xcrun --toolchain ${{ env.TOOLCHAINS }} swift test --verbose
        else
          swift test --verbose
        fi
      env:
        ENABLE_INTEGRATION_TESTS: 1
        IS_CI: 1
